### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by bnbaliga** [r1pper/Topshelf.StartParameters#2]
Hi,

  this is a nice feature which I want to use in my project. Couple of questions though - Are you planning to update the code to work with new version of Top shelf? Secondly if I am passing the parameters while running the console application that wraps the topshelf, while debugging the console application is run with my own custom parameters - I want to make Topsehlf ignore these parameters. Does your extension work this way?

Regards
Baliga

**Comment by Markeli** [comment]
@bnbaliga Are you planning to update? If you change licence I will make pull request with changes.

**Comment by r1pper** [comment]
@Markeli  I changed the license to MIT. However I'm open to suggestions if you think any other license is more suitable.

btw, I made some subtle changes, but nothing special that cannot be merge in the future.

**Comment by r1pper** [comment]
#3 New Topshelf 4.0.2 is supported thanks to @Markeli
