### ISSUE TITLE
Access from Nuget Repo

### ISSUE THREAD

**Issue by mkuklis** [r1pper/Topshelf.StartParameters#4]
Hi There, would it be possible for you to publish `Topshelf.StartParameters` to the https://www.nuget.org? Thank you!

**Comment by r1pper** [comment]
Done!

Nuget Command: **Install-Package TopShelf.StartParameters** 

just give it some time to get indexed.
Link: [https://www.nuget.org/packages/TopShelf.StartParameters/](url)

**Comment by mkuklis** [comment]
Great Thank you so much @r1pper!
